spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ibmproj6
        username: root
        password: yash

    jpa:
        generate-ddl: true
        show-sql: true
        
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQLDialect
